import os
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

# Ensure destination directory exists
OUTPUT_DIR = "data/documents"
os.makedirs(OUTPUT_DIR, exist_ok=True)

POLICIES = {
    "SOP_ENG_Structural_Steel_Safety.pdf": """
    ========================================================================================<br/>
    <b>STANDARD OPERATING PROCEDURE: STRUCTURAL STEEL CAPACITY & SAFETY</b><br/>
    Document ID: SOP-ENG-2026-001 | Revision: 3.2 | Effective Date: Jan 2026<br/>
    ========================================================================================<br/><br/>
    <b>1. PURPOSE & SCOPE</b><br/>
    This standard operating procedure mandates safety parameters and mathematical verification models for structural steel members deployed in high-load industrial infrastructures. Compliance with IS-800 and ASTM A36 standards is mandatory across all design and execution phases.<br/><br/>
    <b>2. MATERIAL CONSTANTS (ASTM A36 STEEL)</b><br/>
    - Yield Strength (Fy): 250 MPa (N/mm²)<br/>
    - Elastic Modulus (E): 200,000 MPa<br/>
    - Density: 7,850 kg/m³<br/>
    - Poisson's Ratio: 0.26<br/><br/>
    <b>3. SAFETY & ALLOWABLE STRESS LIMITS</b><br/>
    Under standard structural load conditions, allowable bending stress must not exceed 66% of the material yield strength:<br/>
    - Formula: Allowable_Stress = 0.66 * Fy<br/>
    - Baseline Limit for Grade A36: Allowable_Stress = 165.0 MPa<br/><br/>
    <b>4. MATHEMATICAL FORMULATION FOR SIMPLY SUPPORTED BEAMS</b><br/>
    To evaluate beam capacity under a central point load:<br/>
    1. Calculate Applied Force (F): Force_N = Mass_kg * 9.81<br/>
    2. Convert Beam Span (L) to millimeters: Span_mm = Span_m * 1000<br/>
    3. Calculate Maximum Bending Moment (M): Moment_Nmm = (Force_N * Span_mm) / 4<br/>
    4. Calculate Actual Bending Stress (sigma): Bending_Stress_MPa = Moment_Nmm / Section_Modulus_Z_mm3<br/><br/>
    <b>5. VERIFICATION & EVALUATION RULE</b><br/>
    - IF Bending_Stress_MPa &lt;= 165.0 MPa: PASS (Structure is safe for operation).<br/>
    - IF Bending_Stress_MPa &gt; 165.0 MPa: FAIL (Exceeds safety capacity; redesign required).
    """,
    "SOP_PIPE_High_Pressure_Pipeline_Hoop_Stress.pdf": """
    ========================================================================================<br/>
    <b>INDUSTRIAL PIPELINE OPERATIONS MANUAL: HOOP STRESS EVALUATION</b><br/>
    Document ID: SOP-PIPE-2026-012 | Revision: 4.0 | Effective Date: Feb 2026<br/>
    ========================================================================================<br/><br/>
    <b>1. APPLICABILITY</b><br/>
    This standard applies strictly to all high-pressure gas and liquid transmission lines composed of API 5L Grade X-52 carbon steel.<br/><br/>
    <b>2. MATERIAL SPECIFICATIONS (API 5L GRADE X-52)</b><br/>
    - Specified Minimum Yield Strength (SMYS): 358 MPa<br/>
    - Ultimate Tensile Strength: 455 MPa<br/><br/>
    <b>3. PRESSURE & STRESS COMPUTATION (BARLOW'S FORMULA)</b><br/>
    Hoop stress generated by internal fluid pressure is calculated using Barlow's Equation:<br/>
    - Formula: Hoop_Stress_MPa = (Pressure_MPa * Internal_Diameter_mm) / (2 * Wall_Thickness_mm)<br/>
    - Unit Conversion: 1 Bar = 0.1 N/mm² (MPa). Pressure supplied in Bar must be multiplied by 0.1.<br/><br/>
    <b>4. SAFETY FACTOR & THRESHOLD PROTOCOL</b><br/>
    In compliance with pipeline safety regulations, operating hoop stress must never exceed 72% of the SMYS:<br/>
    - Allowable Operating Hoop Stress = 0.72 * 358 MPa = 257.76 MPa.<br/><br/>
    <b>5. EMERGENCY ACTION LOGIC</b><br/>
    - IF Calculated_Hoop_Stress &lt;= 257.76 MPa: System is COMPLIANT.<br/>
    - IF Calculated_Hoop_Stress &gt; 257.76 MPa: NON-COMPLIANT. Trigger emergency depressurization (SOP-12-B).
    """,
    "HR_POL_Leave_Accrual_and_Encashment.pdf": """
    ========================================================================================<br/>
    <b>CORPORATE HR POLICY: LEAVE ACCRUAL, ROLLOVER, AND ENCASHMENT</b><br/>
    Document ID: HR-POL-2026-V2 | Section: Employee Benefits | Effective Date: Jan 2026<br/>
    ========================================================================================<br/><br/>
    <b>1. EARNED LEAVE (EL) ACCRUAL STRUCTURE</b><br/>
    - All full-time regular employees accrue Earned Leave (EL) at a fixed rate of 1.75 days per completed calendar month.<br/>
    - Maximum annual accrual across 12 months is 21.0 days.<br/><br/>
    <b>2. YEAR-END CARRY-FORWARD & ROLLOVER RULES</b><br/>
    - The maximum allowable EL balance that can be carried forward into the subsequent calendar year is 10.0 days.<br/>
    - Any balance exceeding 10.0 days at midnight on December 31st is automatically transferred to the encashment pool or forfeited based on employee tenure.<br/><br/>
    <b>3. SICK LEAVE (SL) & CASUAL LEAVE (CL) PARITY</b><br/>
    - Employees receive a flat allocation of 12 days Sick Leave and 8 days Casual Leave annually.<br/>
    - Sick and Casual leaves are non-cumulative and lapse completely at year-end.
    """,
    "SOP_DATACENTER_Thermal_Throttling_Policy.pdf": """
    ========================================================================================<br/>
    <b>DATA CENTER ENVIRONMENTAL & POWER SOP: THERMAL MANAGEMENT</b><br/>
    Document ID: SOP-DC-2026-088 | Revision: 1.1 | Effective Date: Mar 2026<br/>
    ========================================================================================<br/><br/>
    <b>1. PURPOSE & HARDWARE CONSTRAINTS</b><br/>
    To prevent hardware degradation during high-density local AI inference workloads running on air-gapped server racks.<br/><br/>
    <b>2. THERMAL THRESHOLDS</b><br/>
    - Optimal Operating Inlet Temperature: 18°C to 24°C.<br/>
    - Thermal Warning Threshold: 28°C ambient temperature.<br/>
    - Thermal Critical Threshold: 32°C ambient temperature sustained for &gt; 5 minutes.<br/><br/>
    <b>3. COMPUTATIONAL POWER MITIGATION FORMULA</b><br/>
    When ambient rack temperatures exceed 28°C, compute capacity must be throttled down according to:<br/>
    - Throttle_Percentage = (Current_Temp_C - 28) * 12.5<br/>
    - Example: At 32°C, Throttle_Percentage = (32 - 28) * 12.5 = 50% workload reduction.<br/><br/>
    <b>4. SAFETY INTERLOCK</b><br/>
    If rack temperature exceeds 35°C, trigger immediate emergency shutdown of non-essential AI compute nodes.
    """,
    "PROC_POL_Vendor_Selection_Compliance.pdf": """
    ========================================================================================<br/>
    <b>GLOBAL PROCUREMENT POLICY: VENDOR COMPLIANCE & TENDER BINDING</b><br/>
    Document ID: PROC-POL-2026-004 | Revision: 2.0 | Effective Date: Jan 2026<br/>
    ========================================================================================<br/><br/>
    <b>1. MANDATORY VENDOR SELECTION MATRIX</b><br/>
    All corporate procurement requests exceeding $50,000 USD must satisfy three mandatory criteria before purchase order issuance:<br/>
    1. Minimum 3 independent competitive bids submitted.<br/>
    2. Environmental, Social, and Governance (ESG) rating score of at least 70 out of 100.<br/>
    3. Active ISO 27001 Information Security Certification.<br/><br/>
    <b>2. PENALTY & COMPLIANCE VERIFICATION FORMULA</b><br/>
    Tender Approval Status = (Bids_Count &gt;= 3) AND (ESG_Score &gt;= 70) AND (ISO_Certified == True)<br/>
    If any parameter evaluates to False, the procurement requisition is rejected automatically.
    """,
}


def create_pdfs():
    styles = getSampleStyleSheet()
    normal_style = styles["Normal"]
    normal_style.fontSize = 10
    normal_style.leading = 14

    for filename, content in POLICIES.items():
        filepath = os.path.join(OUTPUT_DIR, filename)
        doc = SimpleDocTemplate(filepath, pagesize=letter)
        story = []

        formatted_text = content.replace("\n", "").strip()
        story.append(Paragraph(formatted_text, normal_style))

        doc.build(story)
        print(f"Successfully generated: {filepath}")


if __name__ == "__main__":
    create_pdfs()